# Generated by Django 5.2.1 on 2025-06-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('ec_handler', 'EC Handler'), ('tech_fault_handler', 'Tech Fault Handler'), ('admin', 'Admin')], default=('student', 'Student'), max_length=40),
        ),
    ]
