# Generated by Django 5.2.1 on 2025-06-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_enrollment'),
        ('users', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='modules',
            field=models.ManyToManyField(related_name='enrolled_users', through='modules.Enrollment', to='modules.module'),
        ),
    ]
