# Generated by Django 5.2.1 on 2025-06-03 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('ECS[0-9]{3}[A-Z]')])),
                ('name', models.TextField()),
            ],
        ),
    ]
