# Generated by Django 5.2.1 on 2025-06-04 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechFault',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_submitted', models.DateField(auto_now=True)),
                ('explanation', models.TextField()),
                ('location', models.CharField(choices=[('ITL', 'ITL'), ('ITS', 'ITS'), ('MySIS', 'MySIS'), ('QM+', 'QM+')], default=('ITL', 'ITL'), max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default=('Pending', 'Pending'), max_length=10)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'user_type': 'tech_fault_handler'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tech_faults', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_ticket', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechFaultFileUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tech_fault_evidence/')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tickets.techfault')),
            ],
        ),
    ]
