# Generated by Django 5.2.1 on 2025-06-04 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='techfault',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'user_type': 'tech_fault_handler'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='techfault',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EC',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_submitted', models.DateField(auto_now=True)),
                ('nature_of_circumstance', models.CharField(choices=[('Bereavement', 'Bereavement'), ('Crime', 'Crime'), ('Major unforseeable travel disruption', 'Major unforseeable travel disruption'), ('Mental Health: acute episode', 'Mental Health: acute episode'), ('Mental Health: long-term condition', 'Mental Health: long-term condition'), ('Minor illness/medical reasons', 'Minor illness/medical reasons'), ('Physical Health: long-term condition', 'Physical Health: long-term condition'), ('Severe illness/medical reasons: acute episode', 'Severe illness/medical reasons: acute episode'), ('Other', 'Other')], default=('Other', 'Other'), max_length=50)),
                ('further_explanation', models.TextField()),
                ('assessment_type', models.CharField(choices=[('Demontrastion', 'Demontrastion'), ('In-Module Examination', 'In-Module Examination'), ('Coursework Submission', 'Coursework Submission'), ('Examination', 'Examination')], default=('Demontrastion', 'Demontrastion'), max_length=25)),
                ('assessment_submission_date', models.DateField()),
                ('requested_outcome', models.CharField(choices=[('Non-Submission', 'Non-Submission'), ('Non-Attendance', 'Non-Attendance')], default=('Non-Submission', 'Non-Submission'), max_length=20)),
                ('requested_extended_deadline_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default=('Pending', 'Pending'), max_length=10)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'user_type': 'ec_handler'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('module_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ECFileUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ec_evidence/')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tickets.ec')),
            ],
        ),
    ]
